### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [Readf0x/integral-prompt#5]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by Readf0x** [comment]
Lol, I completely forgot to add a license file! I would like to use the GPLv3, are there any compatibility issues with that?

Unrelated to the licensing, I'm surprised that you would add my very unfinished plugin to an awesome list! Which does make me wonder, what exactly are the requirements to be added to that list? (And how did you even find this?!)

**Comment by Readf0x** [comment]
Having found several GPL licensed plugins in the repo, I'll go ahead and assume that there are no issues.
